from comfy_script.runtime import *
# ComfyUI server/path
# or: load(r'path/to/ComfyUI')
load('http://127.0.0.1:8188/')
from comfy_script.runtime.nodes import *

with Workflow(wait=True):
    int = PrimitiveInt(4)
    float = PrimitiveFloat(1)
    int2 = PrimitiveInt(2)
    model = UNETLoader('wan2.2_i2v_low_noise_14B_fp8_scaled.safetensors', 'default')
    model2 = LoraLoaderModelOnly(model, 'wan2.2_i2v_lightx2v_4steps_lora_v1_low_noise.safetensors', 1.0000000000000002)
    model3 = ModelSamplingSD3(model2, 5.000000000000001)
    clip = CLIPLoader('umt5_xxl_fp8_e4m3fn_scaled.safetensors', 'wan', 'default')
    conditioning = CLIPTextEncode('''a cinematic sunset scene, a tabby cat standing on a high-rise window ledge overlooking a modern city skyline, golden hour sunlight illuminating the cat's fur, soft wind gently moving the cat’s fur and whiskers, the cat slowly looking around and blinking, subtle breathing motion, distant city haze, warm sunlight reflections on glass buildings, atmospheric depth, cinematic lighting, ultra realistic, shallow depth of field, slow camera drift, dramatic skyline, peaceful mood
    subtle motion, gentle wind, slow breathing, cat blinking occasionally, slight head movement, slow cinematic camera push forward, distant atmospheric movement in the city''', clip)
    conditioning2 = CLIPTextEncode('色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走', clip)
    vae = VAELoader('wan_2.1_vae.safetensors')
    image, _ = LoadImage('ComfyUI_temp_xpjlx_00012_.png')
    positive, negative, latent = WanImageToVideo(conditioning, conditioning2, vae, 640, 640, 81, 1, None, image)
    model4 = UNETLoader('wan2.2_i2v_high_noise_14B_fp8_scaled.safetensors', 'default')
    model5 = LoraLoaderModelOnly(model4, 'wan2.2_i2v_lightx2v_4steps_lora_v1_high_noise.safetensors', 1.0000000000000002)
    model6 = ModelSamplingSD3(model5, 5.000000000000001)
    latent = KSamplerAdvanced(model6, 'enable', 415617686755647, int, float, 'euler', 'simple', positive, negative, latent, 0, int2, 'enable')
    latent = KSamplerAdvanced(model3, 'disable', 0, int, float, 'euler', 'simple', positive, negative, latent, int2, int, 'disable')
    image2 = VAEDecode(latent, vae)
    video = CreateVideo(image2, 16, None)
    SaveVideo(video, 'video/Wan2.2_i2v', 'auto', 'auto')
    boolean = PrimitiveBoolean(True)
    # _ = ComfySwitchNode(boolean, model4, model5)
    int3 = PrimitiveInt(20)
    # _ = ComfySwitchNode(boolean, int3, int)
    float2 = PrimitiveFloat(3.5)
    # _ = ComfySwitchNode(boolean, float2, float)
    int4 = PrimitiveInt(10)
    # _ = ComfySwitchNode(boolean, int4, int2)
    # _ = ComfySwitchNode(boolean, model, model2)